/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as InteriorsRouteImport } from './routes/interiors'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InteriorsIndexRouteImport } from './routes/interiors.index'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as InteriorsProcessRouteImport } from './routes/interiors.process'
import { Route as InteriorsJournalRouteImport } from './routes/interiors.journal'
import { Route as StoreSlugIndexRouteImport } from './routes/store.$slug.index'
import { Route as StoreSlugItemIdRouteImport } from './routes/store.$slug.$itemId'
import { Route as InteriorsServicesSlugRouteImport } from './routes/interiors.services.$slug'
import { Route as InteriorsServicesSlugIndexRouteImport } from './routes/interiors.services.$slug.index'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorsRoute = InteriorsRouteImport.update({
  id: '/interiors',
  path: '/interiors',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorsIndexRoute = InteriorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InteriorsRoute,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const InteriorsProcessRoute = InteriorsProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => InteriorsRoute,
} as any)
const InteriorsJournalRoute = InteriorsJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => InteriorsRoute,
} as any)
const StoreSlugIndexRoute = StoreSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreSlugRoute,
} as any)
const StoreSlugItemIdRoute = StoreSlugItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => StoreSlugRoute,
} as any)
const InteriorsServicesSlugRoute = InteriorsServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => InteriorsRoute,
} as any)
const InteriorsServicesSlugIndexRoute =
  InteriorsServicesSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => InteriorsServicesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/interiors': typeof InteriorsRouteWithChildren
  '/store': typeof StoreRouteWithChildren
  '/interiors/journal': typeof InteriorsJournalRoute
  '/interiors/process': typeof InteriorsProcessRoute
  '/store/$slug': typeof StoreSlugRouteWithChildren
  '/interiors/': typeof InteriorsIndexRoute
  '/interiors/services/$slug': typeof InteriorsServicesSlugRouteWithChildren
  '/store/$slug/$itemId': typeof StoreSlugItemIdRoute
  '/store/$slug/': typeof StoreSlugIndexRoute
  '/interiors/services/$slug/': typeof InteriorsServicesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/store': typeof StoreRouteWithChildren
  '/interiors/journal': typeof InteriorsJournalRoute
  '/interiors/process': typeof InteriorsProcessRoute
  '/interiors': typeof InteriorsIndexRoute
  '/store/$slug/$itemId': typeof StoreSlugItemIdRoute
  '/store/$slug': typeof StoreSlugIndexRoute
  '/interiors/services/$slug': typeof InteriorsServicesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/interiors': typeof InteriorsRouteWithChildren
  '/store': typeof StoreRouteWithChildren
  '/interiors/journal': typeof InteriorsJournalRoute
  '/interiors/process': typeof InteriorsProcessRoute
  '/store/$slug': typeof StoreSlugRouteWithChildren
  '/interiors/': typeof InteriorsIndexRoute
  '/interiors/services/$slug': typeof InteriorsServicesSlugRouteWithChildren
  '/store/$slug/$itemId': typeof StoreSlugItemIdRoute
  '/store/$slug/': typeof StoreSlugIndexRoute
  '/interiors/services/$slug/': typeof InteriorsServicesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/interiors'
    | '/store'
    | '/interiors/journal'
    | '/interiors/process'
    | '/store/$slug'
    | '/interiors/'
    | '/interiors/services/$slug'
    | '/store/$slug/$itemId'
    | '/store/$slug/'
    | '/interiors/services/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/store'
    | '/interiors/journal'
    | '/interiors/process'
    | '/interiors'
    | '/store/$slug/$itemId'
    | '/store/$slug'
    | '/interiors/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/bookmarks'
    | '/interiors'
    | '/store'
    | '/interiors/journal'
    | '/interiors/process'
    | '/store/$slug'
    | '/interiors/'
    | '/interiors/services/$slug'
    | '/store/$slug/$itemId'
    | '/store/$slug/'
    | '/interiors/services/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarksRoute: typeof BookmarksRoute
  InteriorsRoute: typeof InteriorsRouteWithChildren
  StoreRoute: typeof StoreRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interiors': {
      id: '/interiors'
      path: '/interiors'
      fullPath: '/interiors'
      preLoaderRoute: typeof InteriorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interiors/': {
      id: '/interiors/'
      path: '/'
      fullPath: '/interiors/'
      preLoaderRoute: typeof InteriorsIndexRouteImport
      parentRoute: typeof InteriorsRoute
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/interiors/process': {
      id: '/interiors/process'
      path: '/process'
      fullPath: '/interiors/process'
      preLoaderRoute: typeof InteriorsProcessRouteImport
      parentRoute: typeof InteriorsRoute
    }
    '/interiors/journal': {
      id: '/interiors/journal'
      path: '/journal'
      fullPath: '/interiors/journal'
      preLoaderRoute: typeof InteriorsJournalRouteImport
      parentRoute: typeof InteriorsRoute
    }
    '/store/$slug/': {
      id: '/store/$slug/'
      path: '/'
      fullPath: '/store/$slug/'
      preLoaderRoute: typeof StoreSlugIndexRouteImport
      parentRoute: typeof StoreSlugRoute
    }
    '/store/$slug/$itemId': {
      id: '/store/$slug/$itemId'
      path: '/$itemId'
      fullPath: '/store/$slug/$itemId'
      preLoaderRoute: typeof StoreSlugItemIdRouteImport
      parentRoute: typeof StoreSlugRoute
    }
    '/interiors/services/$slug': {
      id: '/interiors/services/$slug'
      path: '/services/$slug'
      fullPath: '/interiors/services/$slug'
      preLoaderRoute: typeof InteriorsServicesSlugRouteImport
      parentRoute: typeof InteriorsRoute
    }
    '/interiors/services/$slug/': {
      id: '/interiors/services/$slug/'
      path: '/'
      fullPath: '/interiors/services/$slug/'
      preLoaderRoute: typeof InteriorsServicesSlugIndexRouteImport
      parentRoute: typeof InteriorsServicesSlugRoute
    }
  }
}

interface InteriorsServicesSlugRouteChildren {
  InteriorsServicesSlugIndexRoute: typeof InteriorsServicesSlugIndexRoute
}

const InteriorsServicesSlugRouteChildren: InteriorsServicesSlugRouteChildren = {
  InteriorsServicesSlugIndexRoute: InteriorsServicesSlugIndexRoute,
}

const InteriorsServicesSlugRouteWithChildren =
  InteriorsServicesSlugRoute._addFileChildren(
    InteriorsServicesSlugRouteChildren,
  )

interface InteriorsRouteChildren {
  InteriorsJournalRoute: typeof InteriorsJournalRoute
  InteriorsProcessRoute: typeof InteriorsProcessRoute
  InteriorsIndexRoute: typeof InteriorsIndexRoute
  InteriorsServicesSlugRoute: typeof InteriorsServicesSlugRouteWithChildren
}

const InteriorsRouteChildren: InteriorsRouteChildren = {
  InteriorsJournalRoute: InteriorsJournalRoute,
  InteriorsProcessRoute: InteriorsProcessRoute,
  InteriorsIndexRoute: InteriorsIndexRoute,
  InteriorsServicesSlugRoute: InteriorsServicesSlugRouteWithChildren,
}

const InteriorsRouteWithChildren = InteriorsRoute._addFileChildren(
  InteriorsRouteChildren,
)

interface StoreSlugRouteChildren {
  StoreSlugItemIdRoute: typeof StoreSlugItemIdRoute
  StoreSlugIndexRoute: typeof StoreSlugIndexRoute
}

const StoreSlugRouteChildren: StoreSlugRouteChildren = {
  StoreSlugItemIdRoute: StoreSlugItemIdRoute,
  StoreSlugIndexRoute: StoreSlugIndexRoute,
}

const StoreSlugRouteWithChildren = StoreSlugRoute._addFileChildren(
  StoreSlugRouteChildren,
)

interface StoreRouteChildren {
  StoreSlugRoute: typeof StoreSlugRouteWithChildren
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreSlugRoute: StoreSlugRouteWithChildren,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarksRoute: BookmarksRoute,
  InteriorsRoute: InteriorsRouteWithChildren,
  StoreRoute: StoreRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
